### ISSUE TITLE
wait-db

### ISSUE THREAD

**Issue by paintmeyellow** [ElisDN/demo-project-manager#7]
until docker-compose exec -T manager-postgres pg_isready --timeout=0 --dbname=app ; do sleep 1 ; done
Не всегда работает корректно. Миграции пытаются примениться до того, как поднимается postgres. Тоже самое с mysql.

Решение: https://github.com/vishnubob/wait-for-it
docker-compose exec app /app/docker/scripts/wait-for-it.sh mysql:3306

**Comment by Alek2012** [comment]
@Nikitos096 спасибо огромное, пригодился скрипт, круто что он универсальный
